### ISSUE TITLE
React 0.13.*

### ISSUE THREAD

**Issue by jon49** [daryl/react-node#1]
Any plans on getting this to work with react 0.13?

For `React.DOM.p` I get

```js
{ type: 'p',
  key: null,
  ref: null,
  _owner: null,
  _context: {},
  _store: 
   { props: { value: 'hello!' },
     originalProps: { value: 'hello!' } } }
```

but for `n('p', 'hello!')` I get:

```js
{ type: 'p',
  key: null,
  ref: null,
  _owner: null,
  _context: {},
  _store: { validated: false, props: { children: 'hello!' } } }
```

I love the idea of this project. It makes the API simpler like `Mithril.js` (now if everyone could get on board with `mithril`...).

**Comment by daryl** [comment]
Should be good to go. Let me know if you have any other issues.
